### ISSUE TITLE
improving OpenData flow

### ISSUE THREAD

**Issue by acholyn** [UCL/kapta-mobile#115]
We might not need the seed data for opendata in the dynamodb as we can create tasks from the mobile side. If we want to allow users to generate lots of opendata that's distinct from other opendata entries, we might want to change the task id from `opendata-userId` to something like `opendata-uuid` (as the userId will still be recorded on the created by field, or possibly `opendata-userId-short UUID`. With the former we'd probably have to add sort keys or a new GIS to access the task table by the created by attribute.

We probably also want them to be able to choose from their own previous opendata task entries to add to if they want

**Comment by acholyn** [comment]
The tail part could be separated with / so that we can search for between `opendata-` and `/` to extract the user id more easily

**Comment by acholyn** [comment]
#98 addresses the idea of distinguishing the requests - we just use a regular uuid rather than the user id

**Comment by tcouch** [comment]
closing due to #149
