### ISSUE TITLE
Add pictures in pop up

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#26]
links pics in the chat to locations and display them in the map pop ups

**Comment by tcouch** [comment]
Android chat format with media:
```
25/06/2024, 07:26 - Bob: location: https://maps.google.com/?q=5.1867239,36.1260098
25/06/2024, 07:30 - Bob: adultsmale 6
adultsfemale 9
kidsmale 12
kidsfemale 11
25/06/2024, 07:30 - Bob: Anyagamor Aypa
25/06/2024, 08:07 - Bob: IMG-20240625-WA0000.jpg (file attached)
```

**Comment by acholyn** [comment]
format for ios pictures: 8 digits-PHOTO-yyyy-mm-dd-hh-mm-ss.ext

00000019-PHOTO-2024-09-04-11-12-44.jpg

**Comment by acholyn** [comment]
Possible enhancements for a future version:
- swiping gestures on mobile
- indication of how many images (maybe little dots and the current one is darker)
