### ISSUE TITLE
Change home screen of Kapta

### ISSUE THREAD

**Issue by fmousss** [UCL/kapta-mobile#30]
Could we create a home screen that showcases the 4 steps of the process using screenshots of the actual steps? Users would swipe left four times to view each step. Additionally, we need to include a light dynamic swipe left sign for low-literate users who might not be familiar with this practice. @tcouch @acholyn @MarcosMoreu

**Comment by acholyn** [comment]
would this be opened by tapping a button? having it as the default with no way to bypass wouldn't be a good idea

**Comment by MarcosMoreu** [comment]
We need to think how we make it interactive. We will create a mockup. Meanwhile, we can keep the text instructions with the four steps and add a small button to open this short video tutorial (which we also need to improve) 

https://github.com/user-attachments/assets/f8c55225-c8ba-4be2-bb1e-07df1a5133e2


1 - Create a WhatsApp group 👥💬
2 - Ask the group to share and describe locations 📎📍💬
3 - Click ‘Export chat’ to the Kapta mobile app 💬🗺️
4 - Use and share your WhatsApp Map with Kapta 🗺️💸

**Comment by acholyn** [comment]
can you send me the video on slack? It doesn't seem to work on here

**Comment by acholyn** [comment]
<img width="290" alt="image" src="https://github.com/user-attachments/assets/95ebb354-9515-4351-8dc6-0221cd991d9d">
do you want the instruction font smaller to fit on one line? + other thoughts?

**Comment by fmousss** [comment]
Could you remove the instructions as a list and create a home screen that showcases the 4 steps (one screen per step) of the process using screenshots of the actual steps? Users would swipe left four times to view each step?

**Comment by acholyn** [comment]
same for on desktop? do you want the ask us anything to be persisted across the pages or on the last page?

**Comment by acholyn** [comment]
you could also do them as videos/gifs

**Comment by MarcosMoreu** [comment]
- The home screen display could be improved? Perhaps add some margins and place the buttons closer to the bottom so it is consistent regardless of the language?

![WhatsApp Image 2024-08-22 at 09 02 56](https://github.com/user-attachments/assets/674164fe-adf0-411b-89d0-5f352d08c4d6)
![WhatsApp Image 2024-08-22 at 09 02 55](https://github.com/user-attachments/assets/a08d3d35-10a1-42e8-9b94-7a32f38a38a8)

**Comment by fmousss** [comment]
@MarcosMoreu your GPT is making it wrong it's not "demandez nous n**'**importe quoi" but **"Posez-nous toutes vos questions"**

**Comment by fmousss** [comment]
also, as mentioned earlier, I do not like the little icons after the text. it's adding a lot of weight to the home screen.

**Comment by MarcosMoreu** [comment]
Okay. Let's put the translations on hold until mid next week, so we also get the final translation for Amharic etc.
