### ISSUE TITLE
Logo & splash screen

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#33]
- Change logo color (replace black with white)
- Set red as background color in the home screen icon 
- Set red as backgorund color in the splash screen when app launches
![Kapta Logo final](https://github.com/user-attachments/assets/0d4feb47-ab84-4932-86fa-aad0aba60f80)

**Comment by acholyn** [comment]
can you send this image on slack? I can't download it from here

**Comment by acholyn** [comment]
not entirely sure I understand what the splash screen is. The initial page of the app has a red background

**Comment by fmousss** [comment]
This is how Kapta logo appears on my phone with the updated link you provided. 
![WhatsApp Image 2024-08-20 at 16 54 35_694ecff5](https://github.com/user-attachments/assets/cbe7d8e5-7027-45ac-8cbe-b2e6c563edde)
