### ISSUE TITLE
Upload/open geojson files

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#36]
Allow users to upload/open geojson files (or .txt files which actually geojson), so any Kapta user can visualise a map data file exported with Kapta without the need of being in the WhatsApp group to export it

**Comment by acholyn** [comment]
do you have a sample file you could share for testing?

**Comment by acholyn** [comment]
users can upload a `.geojson` file and it should be parsed correctly, we probably need to add a check for the .txt files to see if they have whatsapp data or just geojson and then direct it to the correct function

**Comment by tcouch** [comment]
So, maybe wrap JSON.parse(file_contents) in a try block and if it fails assume it's a chat? Probably better to go a step further an write a simple geojson schema validator. Maybe such a thing already exists?
