### ISSUE TITLE
Export geojson error & improvements

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#4]
- Add a name "Kapta_" + dateTime 
- Is there a workaround to export it as .geojson instead of .txt? @tcouch 
- Currently the geojson is incorrect >> remove the quotations "" in the coordinates. Like this:
      "geometry": {
        "type": "Point",
        "coordinates": [
          -0.1348319,
          51.524713
        ]
      }
Not:  

      "geometry": {
        "type": "Point",
        "coordinates": [
          "-0.1348319",
          "51.524713"
        ]
      }

**Comment by tcouch** [comment]
@MarcosMoreu by name, do you mean the filename?

**Comment by MarcosMoreu** [comment]
yes @tcouch
