### ISSUE TITLE
Improving users awareness of Map Title

### ISSUE THREAD

**Issue by fmousss** [UCL/kapta-mobile#41]
When users convert the chat into a map, they are prompted to enter a title for it, with the chat bar suggesting "Title of your map." Once the title is entered, it appears at the top of the map.

Issue A: After entering the title, users tend to focus on the chat bar on what they've written and may not notice that the title has been successfully added to the top of the map. @acholyn, do you have any suggestions to help users notice the added title before sharing the map?

Issue B1: After the title has been added, the suggestion in the chat bar should change from "Title of your map" to "Change the title".

Issue B2: update languages accordingly.

- - English: Change the title
- - Spanish: Cambiar el título
- - French: Changer le titre

**Comment by acholyn** [comment]
We could maybe add some sort of animation? Like a pulse/flash? That might draw their attention to the upper space with the title

**Comment by fmousss** [comment]
Sounds good to me. @MarcosMoreu ?

**Comment by MarcosMoreu** [comment]
yeah
