### ISSUE TITLE
GPS button

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#45]
When GPS recenter buttons is clicked, the background colour should be as the initial after x ms (currently it stays as light grey after clicking)

**Comment by acholyn** [comment]
this was done in the priority PR but seems to have been overwritten by one of the PRs merged later in. Is the button enabled after adding a caption?

**Comment by MarcosMoreu** [comment]
Weird. I only modified the languages.js file. Yeah the buttons works fine. it's just the background color issue

**Comment by acholyn** [comment]
I think it was the ui or caching PRs, should be resolved now anyway
