### ISSUE TITLE
Automatic message when no location in the WA chat

### ISSUE THREAD

**Issue by fmousss** [UCL/kapta-mobile#54]
When there is no location collected in the WhatsApp chat, could we get an automatic message in Kapta saying "There is not location in  the chat". It's better than having an empty map.

**Comment by tcouch** [comment]
@acholyn I've started a branch for this 54/handle-no-locations based off of your reactify branch. So far I've made process-text return no features if there are no locations. I guess one option would be to test for that in parseFile and display a dialog or something if there's nothing to display?
