### ISSUE TITLE
Install prompt inform user...

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#57]
It poor connectivity conditions it takes a while until the app is installed, and this will confuse users who can't find the app after click install. Can we inform the user when the app is installed?  If not possible, just add a message in the prompt that it will take a few seconds

**Comment by acholyn** [comment]
don't think this would be possible on iPhone, do android apps notify you when they've been installed? On iPhone we're shown the screen where we can see it downloading, what's the flow on android? We could do something similar maybe?

**Comment by MarcosMoreu** [comment]
I guess it depends on the device settings and android, play store versions etc.
