### ISSUE TITLE
Store if alert has been shown in Desktop/ios

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#64]
To avoid showing the alert everytime.

**Comment by tcouch** [comment]
Which alert is this?

**Comment by MarcosMoreu** [comment]
when iOS or Desktop an alert is shown everytime, which can be annoying for the users.  Perhaps we can keep the alert on first load and then add a message at the top of the home screen? Not sure what the best solution is, but we definetly need to tell users that the app is (as of now) designed for android devices

**Comment by tcouch** [comment]
Hmm weird. I can't see desktoporiosPrompt being used anywhere in `main` at the moment. Has it been taken out?

**Comment by MarcosMoreu** [comment]
we just used 'alert'. Line 132 in main.js. I guess it worked as a temporary solution

**Comment by acholyn** [comment]
we could set this in localStorage (which would survive until explicitly cleared) or could set a cookie (which we can set an expiry on)
