### ISSUE TITLE
Style the PWA installation popup

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#7]
Improve the style of the installation pop up? Perhaps adding the Kapta logo? @acholyn

**Comment by MarcosMoreu** [comment]
On desktop...
![Screenshot from 2024-07-24 11-36-05](https://github.com/user-attachments/assets/e9c9e9d8-324b-4d67-8670-21b71511b5db)

Perhaps reducing the size of the image would fix it?

**Comment by acholyn** [comment]
I've clamped the width of the dialog, if that's still too big I can then also reduce the image size as well
