### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#71]

**Comment by tcouch** [comment]
@MarcosMoreu do you have a google analytics account set up already?

**Comment by tcouch** [comment]
@MarcosMoreu it'd be useful if we could come up with a list of things we'd like to be able to track and to rate these for how important we think they are.

Reading up on this it looks like the new version of Google Analytics (ga4) might allow us to track certain events like chat conversions, social sharing etc. There's a React plugin [react-ga4](https://github.com/codler/react-ga4) which we could use once we've got #72 completed.

**Comment by MarcosMoreu** [comment]
@tcouch I'll share the credentials in a private channel and create a spreadsheet to list the things we want to track. Before we proceed with GA, are there better alternatives to GA out there? does it integrates with AWS?

**Comment by tcouch** [comment]
I imagine it depends on what your priorities are. I'd be inclined to go with GA initially because it's widely adopted and presumably will do what we need. We could investigate other options later.

Having said that, I'll have a look at what AWS offers too.

**Comment by MarcosMoreu** [comment]
Okay, let's use GA. I had a quick look and doesn't seem like AWS has alternative as such, but instead allows to 'integrate' GA in AWS. Need to investigate more though.
