### ISSUE TITLE
Burger tabs & content

### ISSUE THREAD

**Issue by MarcosMoreu** [UCL/kapta-mobile#97]
I know this is still under dev, but sharing here some suggestions:
Tabs:

- About : This can contain the content of both What?, Why? and What's next? in GH
- People: Same as in GH
- Developers: Include the link to GH and also the 'Legal Disclaimer' section about the licence
- Disclaimer: Here we need to write one about UCL/WCL responsiblity on the maps generated with Kapta. We need to speak with experts to write this. Let's leave it empty for now, but basically we need something to cover our backs on how people use Kapta.

**Comment by acholyn** [comment]
have added the what's next to the rest of the content. Do you actually want a developers section? we could just have a linked GH icon and the legal disclaimer links as menu items rather than in a dropdown since they're very short

**Comment by MarcosMoreu** [comment]
okay. Let's do that
